### ISSUE TITLE
Logs show dropped frames (1sec 60 frames) almost every 10 seconds

### ISSUE THREAD

**Issue by Naruske** [YorVeX/xObsBeam#24]
So not sure how this is happening. I have a beefy laptop, AC powered. It is connected to my game PC through a Thunderbolt to 10Gbit connection. The game PC has a USB 3.2 gen 2 to 5Gbit connection. It's only configured for OBS, so nothing else is on that network.

With compression or without compression it seemingly stutters every couple of seconds, sometimes 2, sometimes 10.

**Comment by YorVeX** [comment]
I figure this is mostly my fault for not putting a template here saying this when creating an issue, but for 90% of issues people encounter with Beam I will need a log of both the sender and receiver to be able to investigate what's going on. This will also provide lots of other information that I need, like operating system (and distro/version), OBS version, Beam version, OBS resolution and color format and so on.

In your case, please do a fresh start of both sender and receiver OBS, let it run and transmit a feed for a few minutes, then exit both OBS instances, restart, and upload the previous logs from both OBS instances:
![image](https://github.com/YorVeX/xObsBeam/assets/528974/85df41d7-6754-4132-9d65-f676f55e919c)

Also I am not familiar with connections of two PCs through Thunderbolt, it's very interesting to me though (and probably to others who want to do lossless raw transmission with Beam), can you give me more information on that? A quick Google search just told me there is something called "Thunderbolt Networking", is that what you're using?
![image](https://github.com/YorVeX/xObsBeam/assets/528974/a74df5f6-d2bc-40c5-825c-522fd2c88b6f)

I assume in the system these appear like network adapters? And since you said this is only meant for OBS, am I right that
- you have other standard Ethernet or Wi-Fi network adapters in addition for your normal home network and Internet access?
- you specifically selected the Thunderbolt network adapters in Beam for both the sender and receiver, to ensure the Beam feed is actually sent through this network and not through your normal (e.g. Wi-Fi) adapter?

To rule out a bug in Beam interface selection, do you have a way of verifying that the feed is actually sent through this Thunderbolt connection? If it's Windows, you should see all interfaces in the Task Manager, the big amount of traffic during an active Beam feed should be visible on the Thunderbolt interface. E.g. for me I have this virtual interface and my Wi-Fi interface, so I could say where exactly the traffic is flowing:
![image](https://github.com/YorVeX/xObsBeam/assets/528974/f70417e7-1a6e-49ef-ab47-c6ba08363cb0)

**Comment by Naruske** [comment]
I'm going to create a log for you this afternoon. I'll explain my network setup as of right now. Not really too complicated.

PC > USB A 3.2 GEN 2 (capable of 10gbit) > a QNAP UC5G1T adapter > CAT 7 cable of roughly 1 meter > a OWC Thunderbolt 3 to 10 Gbit adapter > Thunderbolt 3 connection on laptop.

They each have their own IP (192.168.1.1 and 2)

I can verify it was being passed through the adapters. With no compression selected, it was transmitting 1080p60 at 1.5Gbit speed. Fluctuating a lot of course.

I've attempted the stream with compression (tested JPEG, QOI and L24) through my regular home network and that too lagged every couple of seconds.

Laptop has an i7 13800H, 64GB DDR5 RAM, RTX A2000 and it's connected to the charger.
PC is just AMD Ryzen 5800x, 16GB DDR4 RAM, RTX 3080
My OBS at the time had the following: Streamelements overlay (1 piece of text) Webcam 1080p and game capture.

Again, I'll get some logs in about 4-5 hrs.

Thanks!

**Comment by Naruske** [comment]
https://obsproject.com/logs/LyKlRferx9spqPZ2 sender

https://obsproject.com/logs/ZzCrvsmSAjNjVhN5 receiver

**Comment by YorVeX** [comment]
Fixed in 0.8.3, please update to the new version.
