### ISSUE TITLE
The January 3rd version of Beam can no longer be adapted to OBS 30.2.0-Beta-1.

### ISSUE THREAD

**Issue by HuaHua-Technophile** [YorVeX/xObsBeam#34]
Previously, OBS versions 30.1.2 and even lower were running normally. Today (2024.06.08), after updating to OBS 30.2.0-Beta1, OBS can only be launched in safe mode, and Beam cannot properly adapt to the new UI interface of OBS. It has been confirmed that only the Beam plugin is installed, and it is 100% certain that the inability to open the software is due to Beam.

[Crash 2024-06-08 18-13-15.txt](https://github.com/user-attachments/files/15747542/Crash.2024-06-08.18-13-15.txt)

**Comment by YorVeX** [comment]
Thanks for reporting, will look into it as soon as I got time. Probably some breaking changes in OBS we need to adapt to, might be that we simply need a new generated version of the [NetObsBindings library](https://github.com/kostya9/NetObsBindings) that Beam is using for interfacing with OBS.

**Comment by YorVeX** [comment]
Since beta 1 is old news by now I tried with the current 30.2.0 RC1 version and the January Beam v1.0 version is running just fine and also transmitting my test feed:
![image](https://github.com/YorVeX/xObsBeam/assets/528974/183e189f-53e4-4dac-9e1a-0d31421205d2)

Also, according to your attached crash log, Beam isn't involved in the crash. It is listing the OBS websocket plugin though, you might investigate further into that direction. Might want to hit a support channel on the OBS Discord, there is also a channel specifically reporting issues with the beta.
